import { useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ArrowLeftRight, CalendarDays, ChevronRight, Clock3, MapPin, Search, ShieldCheck, TrainFront, Users } from "lucide-react";
import StationAutocomplete from "../components/StationAutocomplete";
const routes = [["NDLS","BCT","New Delhi","Mumbai Central"],["SBC","MAS","Bengaluru","Chennai"],["HWH","NJP","Howrah","New Jalpaiguri"]];
function savedSearch(){try{return JSON.parse(sessionStorage.getItem("lastSearch"))}catch{return null}}
export default function Home(){
 const navigate=useNavigate(), last=savedSearch(); const [from,setFrom]=useState(last?.from||{code:"NDLS",label:"NDLS — New Delhi"}),[to,setTo]=useState(last?.to||{code:"HWH",label:"HWH — Howrah"}),[date,setDate]=useState(last?.date||new Date().toISOString().split("T")[0]),[error,setError]=useState("");
 function search(e){e.preventDefault();if(!from?.code||!to?.code||from.code===to.code){setError("Choose two different stations to continue.");return}sessionStorage.setItem("lastSearch",JSON.stringify({from,to,date}));navigate(`/search?from=${from.code}&to=${to.code}&date=${date}`)}
 function choose([a,b,an,bn]){setFrom({code:a,label:`${a} — ${an}`});setTo({code:b,label:`${b} — ${bn}`})}
 return <main className="rail-home">
  <nav className="rail-nav"><a className="brand" href="/" aria-label="RailYatra home"><span className="brand-mark"><TrainFront size={19}/></span><span>RAIL<span>YATRA</span></span></a><div className="nav-links"><a href="#routes">Explore routes</a><a href="#why">Why RailYatra</a></div><button className="nav-login" type="button">Sign in <ChevronRight size={16}/></button></nav>
  <section className="hero-shell"><div className="hero-copy"><motion.p initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="eyebrow"><span/>India's rail journey, made effortless</motion.p><motion.h1 initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.08}}>Every journey<br/>starts with a <em>seat.</em></motion.h1><motion.p initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.15}} className="hero-intro">Find the train that fits your day, choose your berth, and travel with confidence.</motion.p><div className="hero-note"><ShieldCheck size={16}/>Live availability across 9,000+ stations</div></div>
  <div className="train-stage" aria-label="Saffron Vande Bharat Express"><div className="sun-disc"/><div className="stage-label">THE NEW WAY TO MOVE <span>01 / 04</span></div><div className="train-photo" role="img" aria-label="Saffron Vande Bharat Express passing through a landscape"/><div className="train-caption"><span>VANDE BHARAT</span><b>Saffron. Swift. Made for India.</b></div></div></section>
  <section className="search-wrap" aria-label="Search trains"><form className="search-panel" onSubmit={search}><div className="station-pair"><StationAutocomplete label="From" value={from} onChange={setFrom} placeholder="Leaving from"/><button className="swap" type="button" onClick={()=>{setFrom(to);setTo(from)}} aria-label="Swap stations"><ArrowLeftRight size={18}/></button><StationAutocomplete label="To" value={to} onChange={setTo} placeholder="Going to"/></div><label className="date-field"><span><CalendarDays size={16}/>Date of journey</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="search-button" type="submit"><Search size={18}/>Find trains</button></form>{error&&<p className="form-error">{error}</p>}</section>
  <section className="below-hero" id="routes"><div className="route-heading"><p className="eyebrow"><span/>Go where the country goes</p><h2>Popular right now.</h2></div><div className="route-list">{routes.map(route=><button type="button" onClick={()=>choose(route)} className="route-card" key={`${route[0]}-${route[1]}`}><span className="route-codes">{route[0]} <i/> {route[1]}</span><span>{route[2]} <ArrowLeftRight size={13}/> {route[3]}</span><ChevronRight size={18}/></button>)}</div></section>
  <section className="proof" id="why"><div><Clock3/><b>In real time</b><span>Availability that keeps up with you.</span></div><div><Users/><b>Built for every traveller</b><span>Clear choices, from first search to ticket.</span></div><div><MapPin/><b>India, connected</b><span>Your next station is always within reach.</span></div></section><footer>RailYatra is a portfolio project and is not affiliated with Indian Railways or IRCTC.</footer>
 </main>}
